# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generation.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'tensors_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("generation.proto", :syntax => :proto3) do
    add_message "gooseai.Token" do
      proto3_optional :text, :string, 1
      optional :id, :uint32, 2
    end
    add_message "gooseai.Tokens" do
      repeated :tokens, :message, 1, "gooseai.Token"
      proto3_optional :tokenizer_id, :string, 2
    end
    add_message "gooseai.Artifact" do
      optional :id, :uint64, 1
      optional :type, :enum, 2, "gooseai.ArtifactType"
      optional :mime, :string, 3
      proto3_optional :magic, :string, 4
      optional :index, :uint32, 8
      optional :finish_reason, :enum, 9, "gooseai.FinishReason"
      optional :seed, :uint32, 10
      optional :uuid, :string, 12
      optional :size, :uint64, 13
      oneof :data do
        optional :binary, :bytes, 5
        optional :text, :string, 6
        optional :tokens, :message, 7, "gooseai.Tokens"
        optional :classifier, :message, 11, "gooseai.ClassifierParameters"
        optional :tensor, :message, 14, "tensors.Tensor"
      end
    end
    add_message "gooseai.PromptParameters" do
      proto3_optional :init, :bool, 1
      proto3_optional :weight, :float, 2
    end
    add_message "gooseai.Prompt" do
      proto3_optional :parameters, :message, 1, "gooseai.PromptParameters"
      oneof :prompt do
        optional :text, :string, 2
        optional :tokens, :message, 3, "gooseai.Tokens"
        optional :artifact, :message, 4, "gooseai.Artifact"
      end
    end
    add_message "gooseai.SamplerParameters" do
      proto3_optional :eta, :float, 1
      proto3_optional :sampling_steps, :uint64, 2
      proto3_optional :latent_channels, :uint64, 3
      proto3_optional :downsampling_factor, :uint64, 4
      proto3_optional :cfg_scale, :float, 5
      proto3_optional :init_noise_scale, :float, 6
      proto3_optional :step_noise_scale, :float, 7
    end
    add_message "gooseai.ConditionerParameters" do
      proto3_optional :vector_adjust_prior, :string, 1
      proto3_optional :conditioner, :message, 2, "gooseai.Model"
    end
    add_message "gooseai.ScheduleParameters" do
      proto3_optional :start, :float, 1
      proto3_optional :end, :float, 2
      proto3_optional :value, :float, 3
    end
    add_message "gooseai.StepParameter" do
      optional :scaled_step, :float, 1
      proto3_optional :sampler, :message, 2, "gooseai.SamplerParameters"
      proto3_optional :schedule, :message, 3, "gooseai.ScheduleParameters"
      proto3_optional :guidance, :message, 4, "gooseai.GuidanceParameters"
    end
    add_message "gooseai.Model" do
      optional :architecture, :enum, 1, "gooseai.ModelArchitecture"
      optional :publisher, :string, 2
      optional :dataset, :string, 3
      optional :version, :float, 4
      optional :semantic_version, :string, 5
      optional :alias, :string, 6
    end
    add_message "gooseai.CutoutParameters" do
      repeated :cutouts, :message, 1, "gooseai.CutoutParameters"
      proto3_optional :count, :uint32, 2
      proto3_optional :gray, :float, 3
      proto3_optional :blur, :float, 4
      proto3_optional :size_power, :float, 5
    end
    add_message "gooseai.GuidanceScheduleParameters" do
      optional :duration, :float, 1
      optional :value, :float, 2
    end
    add_message "gooseai.GuidanceInstanceParameters" do
      repeated :models, :message, 2, "gooseai.Model"
      proto3_optional :guidance_strength, :float, 3
      repeated :schedule, :message, 4, "gooseai.GuidanceScheduleParameters"
      proto3_optional :cutouts, :message, 5, "gooseai.CutoutParameters"
      proto3_optional :prompt, :message, 6, "gooseai.Prompt"
    end
    add_message "gooseai.GuidanceParameters" do
      optional :guidance_preset, :enum, 1, "gooseai.GuidancePreset"
      repeated :instances, :message, 2, "gooseai.GuidanceInstanceParameters"
    end
    add_message "gooseai.TransformType" do
      oneof :type do
        optional :diffusion, :enum, 1, "gooseai.DiffusionSampler"
        optional :upscaler, :enum, 2, "gooseai.Upscaler"
      end
    end
    add_message "gooseai.ImageParameters" do
      proto3_optional :height, :uint64, 1
      proto3_optional :width, :uint64, 2
      repeated :seed, :uint32, 3
      proto3_optional :samples, :uint64, 4
      proto3_optional :steps, :uint64, 5
      proto3_optional :transform, :message, 6, "gooseai.TransformType"
      repeated :parameters, :message, 7, "gooseai.StepParameter"
      proto3_optional :masked_area_init, :enum, 8, "gooseai.MaskedAreaInit"
      proto3_optional :weight_method, :enum, 9, "gooseai.WeightMethod"
      proto3_optional :quantize, :bool, 10
    end
    add_message "gooseai.ClassifierConcept" do
      optional :concept, :string, 1
      proto3_optional :threshold, :float, 2
    end
    add_message "gooseai.ClassifierCategory" do
      optional :name, :string, 1
      repeated :concepts, :message, 2, "gooseai.ClassifierConcept"
      proto3_optional :adjustment, :float, 3
      proto3_optional :action, :enum, 4, "gooseai.Action"
      proto3_optional :classifier_mode, :enum, 5, "gooseai.ClassifierMode"
    end
    add_message "gooseai.ClassifierParameters" do
      repeated :categories, :message, 1, "gooseai.ClassifierCategory"
      repeated :exceeds, :message, 2, "gooseai.ClassifierCategory"
      proto3_optional :realized_action, :enum, 3, "gooseai.Action"
    end
    add_message "gooseai.InterpolateParameters" do
      repeated :ratios, :float, 1
      proto3_optional :mode, :enum, 2, "gooseai.InterpolateMode"
    end
    add_message "gooseai.TransformBlend" do
      optional :amount, :float, 1
      optional :target, :message, 2, "gooseai.Artifact"
    end
    add_message "gooseai.TransformColorAdjust" do
      proto3_optional :brightness, :float, 1
      proto3_optional :contrast, :float, 2
      proto3_optional :hue, :float, 3
      proto3_optional :saturation, :float, 4
      proto3_optional :lightness, :float, 5
    end
    add_message "gooseai.TransformColorMatch" do
      optional :color_mode, :enum, 1, "gooseai.ColorMatchMode"
      optional :image, :message, 2, "gooseai.Artifact"
    end
    add_message "gooseai.TransformDepthCalc" do
      proto3_optional :blend_weight, :float, 1
      proto3_optional :blur_radius, :uint32, 2
      proto3_optional :reverse, :bool, 3
    end
    add_message "gooseai.TransformMatrix" do
      repeated :data, :float, 1
    end
    add_message "gooseai.TransformResample" do
      optional :border_mode, :enum, 1, "gooseai.BorderMode"
      optional :transform, :message, 2, "gooseai.TransformMatrix"
      proto3_optional :prev_transform, :message, 3, "gooseai.TransformMatrix"
      proto3_optional :depth_warp, :float, 4
      proto3_optional :export_mask, :bool, 5
    end
    add_message "gooseai.TransformParameters" do
      oneof :transform do
        optional :blend, :message, 1, "gooseai.TransformBlend"
        optional :color_adjust, :message, 2, "gooseai.TransformColorAdjust"
        optional :color_match, :message, 3, "gooseai.TransformColorMatch"
        optional :depth_calc, :message, 4, "gooseai.TransformDepthCalc"
        optional :resample, :message, 5, "gooseai.TransformResample"
      end
    end
    add_message "gooseai.AssetParameters" do
      optional :action, :enum, 1, "gooseai.AssetAction"
      optional :project_id, :string, 2
      optional :use, :enum, 3, "gooseai.AssetUse"
    end
    add_message "gooseai.AnswerMeta" do
      proto3_optional :gpu_id, :string, 1
      proto3_optional :cpu_id, :string, 2
      proto3_optional :node_id, :string, 3
      proto3_optional :engine_id, :string, 4
    end
    add_message "gooseai.Answer" do
      optional :answer_id, :string, 1
      optional :request_id, :string, 2
      optional :received, :uint64, 3
      optional :created, :uint64, 4
      proto3_optional :meta, :message, 6, "gooseai.AnswerMeta"
      repeated :artifacts, :message, 7, "gooseai.Artifact"
    end
    add_message "gooseai.Request" do
      optional :engine_id, :string, 1
      optional :request_id, :string, 2
      optional :requested_type, :enum, 3, "gooseai.ArtifactType"
      repeated :prompt, :message, 4, "gooseai.Prompt"
      proto3_optional :conditioner, :message, 6, "gooseai.ConditionerParameters"
      proto3_optional :extras, :message, 2047, "google.protobuf.Struct"
      oneof :params do
        optional :image, :message, 5, "gooseai.ImageParameters"
        optional :classifier, :message, 7, "gooseai.ClassifierParameters"
        optional :asset, :message, 8, "gooseai.AssetParameters"
        optional :interpolate, :message, 11, "gooseai.InterpolateParameters"
        optional :transform, :message, 12, "gooseai.TransformParameters"
      end
    end
    add_message "gooseai.OnStatus" do
      repeated :reason, :enum, 1, "gooseai.FinishReason"
      proto3_optional :target, :string, 2
      repeated :action, :enum, 3, "gooseai.StageAction"
    end
    add_message "gooseai.Stage" do
      optional :id, :string, 1
      optional :request, :message, 2, "gooseai.Request"
      repeated :on_status, :message, 3, "gooseai.OnStatus"
    end
    add_message "gooseai.ChainRequest" do
      optional :request_id, :string, 1
      repeated :stage, :message, 2, "gooseai.Stage"
    end
    add_enum "gooseai.FinishReason" do
      value :NULL, 0
      value :LENGTH, 1
      value :STOP, 2
      value :ERROR, 3
      value :FILTER, 4
    end
    add_enum "gooseai.ArtifactType" do
      value :ARTIFACT_NONE, 0
      value :ARTIFACT_IMAGE, 1
      value :ARTIFACT_VIDEO, 2
      value :ARTIFACT_TEXT, 3
      value :ARTIFACT_TOKENS, 4
      value :ARTIFACT_EMBEDDING, 5
      value :ARTIFACT_CLASSIFICATIONS, 6
      value :ARTIFACT_MASK, 7
      value :ARTIFACT_LATENT, 8
      value :ARTIFACT_TENSOR, 9
      value :ARTIFACT_DEPTH, 10
    end
    add_enum "gooseai.MaskedAreaInit" do
      value :MASKED_AREA_INIT_ZERO, 0
      value :MASKED_AREA_INIT_RANDOM, 1
      value :MASKED_AREA_INIT_ORIGINAL, 2
    end
    add_enum "gooseai.WeightMethod" do
      value :TEXT_ENCODER, 0
      value :CROSS_ATTENTION, 1
    end
    add_enum "gooseai.DiffusionSampler" do
      value :SAMPLER_DDIM, 0
      value :SAMPLER_DDPM, 1
      value :SAMPLER_K_EULER, 2
      value :SAMPLER_K_EULER_ANCESTRAL, 3
      value :SAMPLER_K_HEUN, 4
      value :SAMPLER_K_DPM_2, 5
      value :SAMPLER_K_DPM_2_ANCESTRAL, 6
      value :SAMPLER_K_LMS, 7
      value :SAMPLER_K_DPMPP_2S_ANCESTRAL, 8
      value :SAMPLER_K_DPMPP_2M, 9
      value :SAMPLER_K_DPMPP_SDE, 10
    end
    add_enum "gooseai.Upscaler" do
      value :UPSCALER_RGB, 0
      value :UPSCALER_GFPGAN, 1
      value :UPSCALER_ESRGAN, 2
    end
    add_enum "gooseai.GuidancePreset" do
      value :GUIDANCE_PRESET_NONE, 0
      value :GUIDANCE_PRESET_SIMPLE, 1
      value :GUIDANCE_PRESET_FAST_BLUE, 2
      value :GUIDANCE_PRESET_FAST_GREEN, 3
      value :GUIDANCE_PRESET_SLOW, 4
      value :GUIDANCE_PRESET_SLOWER, 5
      value :GUIDANCE_PRESET_SLOWEST, 6
    end
    add_enum "gooseai.ModelArchitecture" do
      value :MODEL_ARCHITECTURE_NONE, 0
      value :MODEL_ARCHITECTURE_CLIP_VIT, 1
      value :MODEL_ARCHITECTURE_CLIP_RESNET, 2
      value :MODEL_ARCHITECTURE_LDM, 3
    end
    add_enum "gooseai.Action" do
      value :ACTION_PASSTHROUGH, 0
      value :ACTION_REGENERATE_DUPLICATE, 1
      value :ACTION_REGENERATE, 2
      value :ACTION_OBFUSCATE_DUPLICATE, 3
      value :ACTION_OBFUSCATE, 4
      value :ACTION_DISCARD, 5
    end
    add_enum "gooseai.ClassifierMode" do
      value :CLSFR_MODE_ZEROSHOT, 0
      value :CLSFR_MODE_MULTICLASS, 1
    end
    add_enum "gooseai.InterpolateMode" do
      value :INTERPOLATE_LINEAR, 0
      value :INTERPOLATE_RIFE, 1
      value :INTERPOLATE_VAE_LINEAR, 2
      value :INTERPOLATE_VAE_SLERP, 3
    end
    add_enum "gooseai.BorderMode" do
      value :BORDER_REFLECT, 0
      value :BORDER_REPLICATE, 1
      value :BORDER_WRAP, 2
      value :BORDER_ZERO, 3
    end
    add_enum "gooseai.ColorMatchMode" do
      value :COLOR_MATCH_HSV, 0
      value :COLOR_MATCH_LAB, 1
      value :COLOR_MATCH_RGB, 2
    end
    add_enum "gooseai.AssetAction" do
      value :ASSET_PUT, 0
      value :ASSET_GET, 1
      value :ASSET_DELETE, 2
    end
    add_enum "gooseai.AssetUse" do
      value :ASSET_USE_UNDEFINED, 0
      value :ASSET_USE_INPUT, 1
      value :ASSET_USE_OUTPUT, 2
      value :ASSET_USE_INTERMEDIATE, 3
      value :ASSET_USE_PROJECT, 4
    end
    add_enum "gooseai.StageAction" do
      value :STAGE_ACTION_PASS, 0
      value :STAGE_ACTION_DISCARD, 1
      value :STAGE_ACTION_RETURN, 2
    end
  end
end

module Gooseai
  Token = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Token").msgclass
  Tokens = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Tokens").msgclass
  Artifact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Artifact").msgclass
  PromptParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.PromptParameters").msgclass
  Prompt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Prompt").msgclass
  SamplerParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.SamplerParameters").msgclass
  ConditionerParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ConditionerParameters").msgclass
  ScheduleParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ScheduleParameters").msgclass
  StepParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.StepParameter").msgclass
  Model = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Model").msgclass
  CutoutParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.CutoutParameters").msgclass
  GuidanceScheduleParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.GuidanceScheduleParameters").msgclass
  GuidanceInstanceParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.GuidanceInstanceParameters").msgclass
  GuidanceParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.GuidanceParameters").msgclass
  TransformType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformType").msgclass
  ImageParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ImageParameters").msgclass
  ClassifierConcept = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ClassifierConcept").msgclass
  ClassifierCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ClassifierCategory").msgclass
  ClassifierParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ClassifierParameters").msgclass
  InterpolateParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.InterpolateParameters").msgclass
  TransformBlend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformBlend").msgclass
  TransformColorAdjust = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformColorAdjust").msgclass
  TransformColorMatch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformColorMatch").msgclass
  TransformDepthCalc = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformDepthCalc").msgclass
  TransformMatrix = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformMatrix").msgclass
  TransformResample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformResample").msgclass
  TransformParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.TransformParameters").msgclass
  AssetParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.AssetParameters").msgclass
  AnswerMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.AnswerMeta").msgclass
  Answer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Answer").msgclass
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Request").msgclass
  OnStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.OnStatus").msgclass
  Stage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Stage").msgclass
  ChainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ChainRequest").msgclass
  FinishReason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.FinishReason").enummodule
  ArtifactType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ArtifactType").enummodule
  MaskedAreaInit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.MaskedAreaInit").enummodule
  WeightMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.WeightMethod").enummodule
  DiffusionSampler = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.DiffusionSampler").enummodule
  Upscaler = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Upscaler").enummodule
  GuidancePreset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.GuidancePreset").enummodule
  ModelArchitecture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ModelArchitecture").enummodule
  Action = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.Action").enummodule
  ClassifierMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ClassifierMode").enummodule
  InterpolateMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.InterpolateMode").enummodule
  BorderMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.BorderMode").enummodule
  ColorMatchMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.ColorMatchMode").enummodule
  AssetAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.AssetAction").enummodule
  AssetUse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.AssetUse").enummodule
  StageAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gooseai.StageAction").enummodule
end
